version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/webapp/

hooks:
  AfterInstall:
    - location: ./afterInstall.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: ./beforeInstall.sh
      timeout: 180
      runas: ubuntu
    
